In [2]:
from operator import rshift
import cv2 as cv 
import numpy as np
import mediapipe as mp 


In [3]:
# mp_face_mesh = mp.solutions.face_mesh
# LEFT_EYE =[ 362, 382, 381, 380, 374, 373, 390, 249, 263, 466, 388, 387, 386, 385,384, 398 ]
# # right eyes indices
# RIGHT_EYE=[ 33, 7, 163, 144, 145, 153, 154, 155, 133, 173, 157, 158, 159, 160, 161 , 246 ] 
# LEFT_IRIS = [474,475, 476, 477]
# RIGHT_IRIS = [469, 470, 471, 472]
# cap = cv.VideoCapture(0)
# with mp_face_mesh.FaceMesh(
#     max_num_faces=1,
#     refine_landmarks=True,
#     min_detection_confidence=0.5,
#     min_tracking_confidence=0.5
# ) as face_mesh:
#     while True:
#         ret, frame = cap.read()
#         if not ret:
#             break
#         frame = cv.flip(frame, 1)
#         rgb_frame = cv.cvtColor(frame, cv.COLOR_BGR2RGB)
#         img_h, img_w = frame.shape[:2]
#         results = face_mesh.process(rgb_frame)
#         if results.multi_face_landmarks:
#             # print(results.multi_face_landmarks[0].landmark)
#             mesh_points=np.array([np.multiply([p.x, p.y], [img_w, img_h]).astype(int) for p in results.multi_face_landmarks[0].landmark])
#             # print(mesh_points.shape)
#             cv.polylines(frame, [mesh_points[LEFT_IRIS]], True, (0,255,0), 1, cv.LINE_AA)
#             cv.polylines(frame, [mesh_points[RIGHT_IRIS]], True, (0,255 ,0), 1, cv.LINE_AA)
#             (l_cx, l_cy), l_radius = cv.minEnclosingCircle(mesh_points[LEFT_IRIS])
#             (r_cx, r_cy), r_radius = cv.minEnclosingCircle(mesh_points[RIGHT_IRIS])
#             center_left = np.array([l_cx, l_cy], dtype=np.int32)
#             center_right = np.array([r_cx, r_cy], dtype=np.int32)
#             cv.circle(frame, center_left, int(l_radius), (255,0,255), 1, cv.LINE_AA)
#             cv.circle(frame, center_right, int(r_radius), (255,0,255), 1, cv.LINE_AA)
            
#         cv.imshow('img', frame)
#         key = cv.waitKey(1)
#         if key ==ord('q'):
#             break
# cap.release()
# cv.destroyAllWindows()

## Understanding the code

In [7]:
mp_face_mesh = mp.solutions.face_mesh
LEFT_EYE =[ 362, 382, 381, 380, 374, 373, 390, 249, 263, 466, 388, 387, 386, 385,384, 398 ]
# right eyes indices
RIGHT_EYE=[ 33, 7, 163, 144, 145, 153, 154, 155, 133, 173, 157, 158, 159, 160, 161 , 246 ] 
LEFT_IRIS = [474,475, 476, 477]
RIGHT_IRIS = [469, 470, 471, 472]
cap = cv.VideoCapture(0)
with mp_face_mesh.FaceMesh(
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
) as face_mesh:
    while True:
        ret, frame = cap.read()
        #print('frame :',frame)
        if not ret:
            break
        frame = cv.flip(frame, 1)
        rgb_frame = cv.cvtColor(frame, cv.COLOR_BGR2RGB)
        img_h, img_w = frame.shape[:2]
        results = face_mesh.process(rgb_frame)
        if results.multi_face_landmarks:
            # print(results.multi_face_landmarks[0].landmark)
            mesh_points=np.array([np.multiply([p.x, p.y], [img_w, img_h]).astype(int) for p in results.multi_face_landmarks[0].landmark])
            # print(mesh_points.shape)
            (l_cx, l_cy), l_radius = cv.minEnclosingCircle(mesh_points[LEFT_IRIS])
            (r_cx, r_cy), r_radius = cv.minEnclosingCircle(mesh_points[RIGHT_IRIS])
            center_left = np.array([l_cx, l_cy], dtype=np.int32)
            center_right = np.array([r_cx, r_cy], dtype=np.int32)
            cv.circle(frame, center_left, int(l_radius), (255,0,255), 1, cv.LINE_AA)
            cv.circle(frame, center_right, int(r_radius), (255,0,255), 1, cv.LINE_AA)
            
        cv.imshow('img', frame)
        key = cv.waitKey(1)
        if key ==ord('q'):
            break
cap.release()
cv.destroyAllWindows()

frame : [[[178 141 110]
  [172 142 109]
  [166 145 108]
  ...
  [119 119 107]
  [124 121 105]
  [126 122 106]]

 [[181 143 110]
  [176 143 105]
  [172 146 103]
  ...
  [116 119 108]
  [119 119 106]
  [120 121 107]]

 [[183 142 112]
  [181 143 108]
  [180 146 106]
  ...
  [110 119 109]
  [111 119 105]
  [111 119 104]]

 ...

 [[ 73  46  23]
  [ 70  49  30]
  [ 62  47  33]
  ...
  [202 194 193]
  [203 192 189]
  [200 189 185]]

 [[ 81  48  26]
  [ 76  48  30]
  [ 71  49  35]
  ...
  [201 195 195]
  [202 193 190]
  [200 191 187]]

 [[ 83  52  27]
  [ 78  51  31]
  [ 74  51  35]
  ...
  [199 197 195]
  [200 196 192]
  [199 195 191]]]
frame : [[[163 141 118]
  [167 141 120]
  [171 142 122]
  ...
  [102 118 116]
  [102 120 119]
  [100 119 118]]

 [[164 142 119]
  [168 142 117]
  [172 142 115]
  ...
  [101 118 120]
  [102 120 121]
  [101 119 119]]

 [[164 142 117]
  [170 145 117]
  [174 144 113]
  ...
  [ 99 120 121]
  [ 99 119 119]
  [ 99 119 119]]

 ...

 [[ 55  51  30]
  [ 62  50  30]
  [ 

  [207 198 189]]]
frame : [[[157 144 118]
  [158 144 114]
  [160 145 110]
  ...
  [ 90 118 108]
  [ 93 121 109]
  [ 94 122 110]]

 [[159 145 116]
  [161 145 115]
  [163 145 113]
  ...
  [ 98 120 110]
  [ 99 122 110]
  [ 99 122 110]]

 [[166 146 116]
  [165 145 115]
  [166 146 116]
  ...
  [100 120 109]
  [102 121 107]
  [102 121 107]]

 ...

 [[ 71  46  35]
  [ 68  47  34]
  [ 67  50  35]
  ...
  [201 199 192]
  [203 198 190]
  [202 197 188]]

 [[ 75  51  38]
  [ 72  52  36]
  [ 69  53  34]
  ...
  [199 200 192]
  [201 198 190]
  [200 197 188]]

 [[ 77  56  39]
  [ 76  56  37]
  [ 75  57  36]
  ...
  [201 200 195]
  [202 199 193]
  [200 197 190]]]
frame : [[[166 141 121]
  [162 144 122]
  [156 145 121]
  ...
  [109 120 119]
  [107 119 118]
  [108 120 119]]

 [[165 142 122]
  [161 145 121]
  [155 145 116]
  ...
  [108 120 118]
  [105 119 116]
  [106 121 117]]

 [[166 144 121]
  [164 145 118]
  [161 146 113]
  ...
  [107 120 118]
  [105 119 116]
  [106 121 117]]

 ...

 [[ 65  47  26]
  

frame : [[[157 147 109]
  [161 145 110]
  [166 144 112]
  ...
  [101 121 111]
  [101 120 114]
  [101 120 114]]

 [[162 148 110]
  [164 146 110]
  [167 145 111]
  ...
  [103 124 113]
  [101 121 112]
  [ 98 119 110]]

 [[166 148 109]
  [168 148 110]
  [170 148 112]
  ...
  [102 123 111]
  [101 121 110]
  [ 98 119 108]]

 ...

 [[ 64  54  27]
  [ 62  54  26]
  [ 59  52  23]
  ...
  [198 197 189]
  [196 193 187]
  [191 187 181]]

 [[ 63  51  27]
  [ 63  50  24]
  [ 62  48  20]
  ...
  [197 197 189]
  [195 195 186]
  [190 189 180]]

 [[ 63  51  32]
  [ 63  50  30]
  [ 63  48  26]
  ...
  [198 196 189]
  [197 195 186]
  [195 193 184]]]
frame : [[[160 144 112]
  [162 146 113]
  [163 146 111]
  ...
  [ 99 120 117]
  [ 99 122 110]
  [ 97 121 108]]

 [[160 144 112]
  [164 146 111]
  [167 147 107]
  ...
  [ 95 118 113]
  [ 99 121 112]
  [ 98 120 111]]

 [[164 145 108]
  [167 145 107]
  [173 148 107]
  ...
  [ 95 117 112]
  [ 98 118 112]
  [100 119 113]]

 ...

 [[ 68  45  35]
  [ 69  44  37]
  [ 

frame : [[[167 145 111]
  [166 146 109]
  [165 147 107]
  ...
  [ 87 123  99]
  [ 93 123  93]
  [ 94 123  92]]

 [[167 145 111]
  [167 146 110]
  [167 146 109]
  ...
  [ 94 121 110]
  [100 119 106]
  [101 119 106]]

 [[169 146 109]
  [170 146 109]
  [169 146 109]
  ...
  [104 120 114]
  [108 119 111]
  [107 118 110]]

 ...

 [[ 61  47  39]
  [ 62  45  35]
  [ 62  42  28]
  ...
  [199 195 186]
  [198 192 181]
  [195 188 177]]

 [[ 63  48  42]
  [ 63  46  39]
  [ 65  45  35]
  ...
  [203 197 188]
  [201 193 182]
  [200 190 179]]

 [[ 63  50  47]
  [ 68  52  45]
  [ 70  50  38]
  ...
  [204 197 188]
  [204 195 184]
  [203 194 183]]]
frame : [[[174 148 102]
  [171 147  99]
  [171 149  98]
  ...
  [107 115 114]
  [106 115 112]
  [108 118 114]]

 [[170 146 103]
  [170 146 102]
  [170 147 101]
  ...
  [108 117 117]
  [106 118 116]
  [107 119 117]]

 [[166 145 108]
  [166 144 107]
  [168 145 108]
  ...
  [108 120 118]
  [106 121 117]
  [106 121 117]]

 ...

 [[ 74  44  26]
  [ 75  42  24]
  [ 

  [201 192 190]]]
frame : [[[165 145 113]
  [165 146 111]
  [165 146 109]
  ...
  [114 118 111]
  [116 119 109]
  [117 119 109]]

 [[164 144 112]
  [165 144 110]
  [167 146 109]
  ...
  [115 119 109]
  [116 119 109]
  [117 119 109]]

 [[166 144 112]
  [167 144 110]
  [168 145 108]
  ...
  [114 118 107]
  [116 119 107]
  [117 119 107]]

 ...

 [[ 61  46  34]
  [ 65  47  35]
  [ 69  46  35]
  ...
  [203 196 187]
  [196 193 187]
  [193 191 185]]

 [[ 66  48  34]
  [ 67  48  34]
  [ 70  49  32]
  ...
  [200 196 187]
  [197 197 185]
  [194 195 183]]

 [[ 66  51  35]
  [ 69  53  34]
  [ 71  53  32]
  ...
  [199 196 187]
  [198 198 187]
  [196 197 185]]]
frame : [[[166 142 117]
  [166 141 120]
  [167 142 124]
  ...
  [104 122 113]
  [105 121 110]
  [105 121 110]]

 [[166 142 117]
  [167 143 119]
  [168 144 121]
  ...
  [102 121 115]
  [105 120 114]
  [105 120 114]]

 [[171 143 118]
  [171 143 118]
  [172 145 121]
  ...
  [ 99 121 117]
  [102 118 116]
  [102 118 117]]

 ...

 [[ 63  53  20]
  

frame : [[[164 143 104]
  [162 143 100]
  [162 145  99]
  ...
  [108 122 107]
  [111 122 105]
  [112 122 105]]

 [[164 143 104]
  [163 142 101]
  [164 144 100]
  ...
  [103 122 107]
  [105 122 107]
  [105 122 107]]

 [[169 143 107]
  [167 143 104]
  [167 145 103]
  ...
  [ 96 123 107]
  [ 99 123 107]
  [ 99 123 107]]

 ...

 [[ 49  49  22]
  [ 51  49  27]
  [ 53  47  32]
  ...
  [201 193 191]
  [202 193 191]
  [198 189 188]]

 [[ 52  51  24]
  [ 52  51  25]
  [ 55  52  27]
  ...
  [203 196 192]
  [202 193 190]
  [200 191 187]]

 [[ 52  53  30]
  [ 55  56  29]
  [ 56  57  25]
  ...
  [203 197 193]
  [202 197 190]
  [200 194 188]]]
frame : [[[165 145 115]
  [166 146 114]
  [167 148 113]
  ...
  [111 118 114]
  [103 120 116]
  [103 121 117]]

 [[163 144 116]
  [165 147 118]
  [165 147 117]
  ...
  [111 119 117]
  [103 119 118]
  [102 119 118]]

 [[164 146 116]
  [165 146 116]
  [166 146 116]
  ...
  [108 119 118]
  [103 119 118]
  [101 118 116]]

 ...

 [[ 74  46  30]
  [ 72  46  29]
  [ 

  [201 195 191]]]
frame : [[[168 143 125]
  [171 142 126]
  [171 141 125]
  ...
  [102 121 115]
  [107 122 118]
  [106 120 117]]

 [[167 144 128]
  [169 144 127]
  [167 142 124]
  ...
  [102 121 116]
  [107 122 118]
  [108 122 118]]

 [[165 144 128]
  [168 145 127]
  [167 145 124]
  ...
  [100 120 115]
  [105 122 118]
  [104 121 117]]

 ...

 [[ 65  47  28]
  [ 66  48  23]
  [ 66  48  18]
  ...
  [204 195 191]
  [204 193 191]
  [203 191 191]]

 [[ 71  53  21]
  [ 68  52  15]
  [ 68  52  12]
  ...
  [203 197 192]
  [199 195 191]
  [198 195 191]]

 [[ 73  55  14]
  [ 73  57  13]
  [ 71  56  12]
  ...
  [202 199 192]
  [200 200 191]
  [197 198 188]]]
frame : [[[155 147 109]
  [154 146 109]
  [155 145 110]
  ...
  [ 92 115 125]
  [ 99 117 125]
  [ 99 117 125]]

 [[155 147 111]
  [155 145 112]
  [158 144 115]
  ...
  [ 98 115 121]
  [102 116 122]
  [103 117 123]]

 [[157 145 116]
  [158 143 116]
  [159 142 116]
  ...
  [103 116 117]
  [102 117 118]
  [103 119 119]]

 ...

 [[ 71  51  28]
  

frame : [[[165 143 109]
  [167 142 108]
  [170 141 108]
  ...
  [102 125 105]
  [ 98 126 103]
  [ 96 125 101]]

 [[166 144 110]
  [167 143 109]
  [169 143 109]
  ...
  [102 125 108]
  [ 98 125 104]
  [ 96 124 103]]

 [[166 144 110]
  [169 146 110]
  [173 147 110]
  ...
  [103 125 110]
  [100 124 106]
  [ 97 122 104]]

 ...

 [[ 68  44  31]
  [ 71  46  30]
  [ 75  48  28]
  ...
  [198 197 191]
  [196 193 187]
  [194 191 184]]

 [[ 72  45  32]
  [ 74  47  29]
  [ 76  50  25]
  ...
  [202 199 194]
  [199 195 191]
  [196 193 189]]

 [[ 74  48  34]
  [ 74  50  30]
  [ 75  54  27]
  ...
  [203 199 193]
  [200 196 192]
  [197 194 190]]]
frame : [[[165 143 109]
  [167 142 108]
  [170 141 108]
  ...
  [102 125 105]
  [ 98 126 103]
  [ 96 125 101]]

 [[166 144 110]
  [167 143 109]
  [169 143 109]
  ...
  [102 125 108]
  [ 98 125 104]
  [ 96 124 103]]

 [[166 144 110]
  [169 146 110]
  [173 147 110]
  ...
  [103 125 110]
  [100 124 106]
  [ 97 122 104]]

 ...

 [[ 68  44  31]
  [ 71  46  30]
  [ 

frame : [[[166 145 108]
  [167 145 113]
  [167 144 116]
  ...
  [ 96 123 107]
  [100 122 104]
  [100 122 104]]

 [[170 144 108]
  [169 143 112]
  [168 143 115]
  ...
  [100 121 107]
  [105 120 105]
  [106 120 104]]

 [[171 145 111]
  [170 145 113]
  [170 145 116]
  ...
  [102 119 108]
  [107 118 108]
  [109 119 109]]

 ...

 [[ 69  48  29]
  [ 67  45  33]
  [ 65  44  37]
  ...
  [210 198 188]
  [215 197 185]
  [211 192 180]]

 [[ 75  46  33]
  [ 74  44  37]
  [ 74  42  41]
  ...
  [215 198 185]
  [217 197 183]
  [215 195 181]]

 [[ 79  46  33]
  [ 81  44  38]
  [ 81  43  42]
  ...
  [215 198 185]
  [215 197 183]
  [214 196 182]]]
frame : [[[170 147 110]
  [172 147 109]
  [175 147 109]
  ...
  [110 120 108]
  [111 119 105]
  [111 119 104]]

 [[169 146 107]
  [171 146 107]
  [174 146 107]
  ...
  [110 120 106]
  [111 119 105]
  [111 119 104]]

 [[168 148 109]
  [169 146 107]
  [173 147 109]
  ...
  [108 120 107]
  [110 117 105]
  [112 118 106]]

 ...

 [[ 79  44  27]
  [ 78  46  28]
  [ 

frame : [[[168 143 104]
  [168 143 102]
  [168 144 100]
  ...
  [ 99 117 121]
  [106 116 120]
  [107 116 120]]

 [[167 145 103]
  [168 145 103]
  [168 144 100]
  ...
  [105 118 120]
  [110 117 116]
  [111 117 116]]

 [[170 149 105]
  [169 146 103]
  [169 145 102]
  ...
  [107 119 118]
  [110 118 115]
  [111 118 114]]

 ...

 [[ 67  44  26]
  [ 68  48  24]
  [ 70  52  21]
  ...
  [201 199 189]
  [199 196 189]
  [195 192 186]]

 [[ 71  46  25]
  [ 72  50  22]
  [ 72  53  18]
  ...
  [202 201 190]
  [200 197 188]
  [199 196 187]]

 [[ 73  51  30]
  [ 75  53  25]
  [ 76  55  18]
  ...
  [202 200 191]
  [202 197 190]
  [203 198 192]]]
frame : [[[169 144 116]
  [174 146 114]
  [177 146 110]
  ...
  [ 98 121 118]
  [ 98 122 115]
  [ 96 121 114]]

 [[169 143 118]
  [172 146 115]
  [173 147 110]
  ...
  [103 119 117]
  [102 122 115]
  [100 120 114]]

 [[169 143 120]
  [168 144 115]
  [168 147 110]
  ...
  [107 119 115]
  [105 120 112]
  [105 121 112]]

 ...

 [[ 63  53  26]
  [ 62  50  29]
  [ 

frame : [[[149 148 103]
  [159 147 104]
  [167 144 105]
  ...
  [104 117 124]
  [104 116 122]
  [103 115 121]]

 [[154 150 105]
  [160 148 106]
  [166 145 108]
  ...
  [107 118 124]
  [105 117 123]
  [104 116 122]]

 [[160 149 107]
  [166 149 109]
  [168 147 110]
  ...
  [109 119 122]
  [108 119 122]
  [107 118 121]]

 ...

 [[ 55  48  28]
  [ 59  47  30]
  [ 63  46  32]
  ...
  [193 195 186]
  [193 193 184]
  [193 193 184]]

 [[ 60  47  23]
  [ 66  48  29]
  [ 71  47  31]
  ...
  [196 197 186]
  [197 196 184]
  [198 195 184]]

 [[ 61  49  23]
  [ 68  50  27]
  [ 76  51  31]
  ...
  [203 198 186]
  [203 197 184]
  [203 197 184]]]
frame : [[[173 146 112]
  [177 147 112]
  [178 145 109]
  ...
  [106 118 121]
  [104 116 122]
  [102 115 121]]

 [[174 147 115]
  [176 147 113]
  [178 147 112]
  ...
  [106 121 122]
  [104 119 122]
  [104 119 123]]

 [[174 147 115]
  [174 147 114]
  [174 147 113]
  ...
  [104 123 121]
  [105 121 120]
  [105 121 120]]

 ...

 [[ 71  48  29]
  [ 68  48  30]
  [ 

frame : [[[159 148 117]
  [158 148 115]
  [158 148 112]
  ...
  [105 116 120]
  [109 117 121]
  [109 117 121]]

 [[157 146 113]
  [158 147 113]
  [160 147 112]
  ...
  [105 119 118]
  [108 120 119]
  [108 120 119]]

 [[159 146 113]
  [161 147 112]
  [162 148 110]
  ...
  [106 119 117]
  [108 120 119]
  [108 120 119]]

 ...

 [[ 75  45  16]
  [ 71  44  19]
  [ 69  45  24]
  ...
  [204 197 193]
  [197 194 188]
  [195 192 185]]

 [[ 76  47  23]
  [ 73  46  23]
  [ 72  47  26]
  ...
  [203 199 194]
  [197 195 191]
  [194 193 189]]

 [[ 75  52  34]
  [ 72  50  32]
  [ 71  50  32]
  ...
  [205 199 193]
  [197 195 191]
  [196 195 191]]]
frame : [[[163 144 116]
  [165 144 117]
  [167 144 116]
  ...
  [ 98 120 111]
  [100 120 111]
  [ 99 119 110]]

 [[165 145 115]
  [166 144 115]
  [167 144 115]
  ...
  [101 121 111]
  [100 120 109]
  [ 98 119 108]]

 [[166 147 110]
  [167 147 113]
  [167 145 113]
  ...
  [101 121 110]
  [100 120 109]
  [100 120 109]]

 ...

 [[ 73  43  32]
  [ 71  45  31]
  [ 

frame : [[[155 147 109]
  [155 146 103]
  [157 145  99]
  ...
  [109 122 115]
  [108 125 114]
  [107 123 112]]

 [[160 147 112]
  [159 146 107]
  [159 145 103]
  ...
  [105 124 113]
  [105 124 111]
  [105 124 111]]

 [[164 147 112]
  [164 148 111]
  [162 146 106]
  ...
  [104 124 112]
  [105 124 111]
  [104 123 110]]

 ...

 [[ 70  47  26]
  [ 70  47  31]
  [ 69  46  35]
  ...
  [195 197 191]
  [190 196 191]
  [187 194 189]]

 [[ 71  48  28]
  [ 69  47  31]
  [ 68  48  36]
  ...
  [198 199 193]
  [194 195 191]
  [193 194 190]]

 [[ 71  53  32]
  [ 69  51  35]
  [ 68  50  38]
  ...
  [201 201 193]
  [200 199 193]
  [199 198 191]]]
frame : [[[166 143 115]
  [166 143 116]
  [166 143 115]
  ...
  [106 116 117]
  [107 119 118]
  [107 119 117]]

 [[167 144 116]
  [166 143 115]
  [166 143 113]
  ...
  [107 116 114]
  [108 117 116]
  [109 118 118]]

 [[167 147 117]
  [165 145 114]
  [165 145 113]
  ...
  [109 119 112]
  [111 119 114]
  [110 118 113]]

 ...

 [[ 59  50  30]
  [ 62  50  28]
  [ 

  [203 195 191]]]
frame : [[[165 145 103]
  [162 146 107]
  [158 145 110]
  ...
  [116 117 115]
  [116 117 115]
  [118 118 116]]

 [[164 146 106]
  [162 146 107]
  [161 147 109]
  ...
  [114 120 115]
  [113 120 112]
  [114 120 112]]

 [[164 146 106]
  [167 148 109]
  [167 149 112]
  ...
  [113 120 115]
  [111 120 112]
  [110 119 111]]

 ...

 [[ 68  47  12]
  [ 69  47  11]
  [ 69  48  11]
  ...
  [204 195 189]
  [203 193 185]
  [199 190 181]]

 [[ 76  49  17]
  [ 75  49  13]
  [ 76  51  12]
  ...
  [212 196 194]
  [210 193 188]
  [208 191 185]]

 [[ 79  51  24]
  [ 80  53  21]
  [ 77  51  15]
  ...
  [212 197 191]
  [211 194 189]
  [212 194 189]]]
frame : [[[167 145 113]
  [167 145 113]
  [167 145 113]
  ...
  [106 119 122]
  [106 119 122]
  [106 119 122]]

 [[168 145 118]
  [169 145 119]
  [168 145 119]
  ...
  [103 120 120]
  [104 120 121]
  [103 119 119]]

 [[170 145 118]
  [171 145 118]
  [169 143 118]
  ...
  [102 120 119]
  [103 119 118]
  [103 119 117]]

 ...

 [[ 54  48  33]
  

frame : [[[161 143 110]
  [158 144 108]
  [158 146 108]
  ...
  [ 97 121 107]
  [ 96 123 105]
  [ 96 124 105]]

 [[161 141 116]
  [160 143 112]
  [160 145 110]
  ...
  [ 96 121 113]
  [ 95 121 107]
  [ 96 123 108]]

 [[162 143 117]
  [162 145 116]
  [162 147 114]
  ...
  [ 95 120 116]
  [ 95 120 111]
  [ 97 121 112]]

 ...

 [[ 67  45  22]
  [ 69  43  20]
  [ 73  42  20]
  ...
  [208 202 197]
  [204 202 193]
  [197 195 186]]

 [[ 70  50  29]
  [ 71  45  26]
  [ 76  43  26]
  ...
  [204 200 196]
  [201 200 194]
  [197 197 190]]

 [[ 71  53  32]
  [ 76  53  32]
  [ 82  52  32]
  ...
  [207 199 196]
  [203 200 196]
  [202 199 194]]]
frame : [[[162 145 119]
  [159 148 122]
  [153 147 121]
  ...
  [112 118 113]
  [107 120 112]
  [106 120 112]]

 [[161 144 118]
  [158 146 117]
  [154 147 116]
  ...
  [112 120 112]
  [109 121 110]
  [109 121 110]]

 [[161 145 116]
  [158 146 113]
  [156 148 110]
  ...
  [109 120 111]
  [107 121 109]
  [107 121 108]]

 ...

 [[ 62  45  31]
  [ 60  46  38]
  [ 

frame : [[[156 143 112]
  [160 145 109]
  [162 147 103]
  ...
  [106 117 118]
  [104 120 119]
  [103 120 119]]

 [[160 144 112]
  [162 147 109]
  [163 148 104]
  ...
  [107 119 118]
  [105 119 118]
  [105 119 118]]

 [[162 144 112]
  [164 148 110]
  [164 149 105]
  ...
  [109 120 117]
  [107 119 116]
  [106 118 115]]

 ...

 [[ 63  47  30]
  [ 64  50  30]
  [ 65  52  28]
  ...
  [207 194 191]
  [205 191 190]
  [200 187 186]]

 [[ 62  49  28]
  [ 63  51  28]
  [ 65  52  28]
  ...
  [207 195 192]
  [204 193 191]
  [201 190 189]]

 [[ 60  49  29]
  [ 64  51  30]
  [ 67  52  28]
  ...
  [207 197 193]
  [204 195 194]
  [203 194 193]]]
frame : [[[166 141 111]
  [166 143 109]
  [166 145 108]
  ...
  [ 99 120 106]
  [ 96 120 106]
  [ 96 120 106]]

 [[166 141 111]
  [166 143 110]
  [166 144 110]
  ...
  [100 119 108]
  [100 119 108]
  [102 120 109]]

 [[166 140 115]
  [166 142 113]
  [167 145 113]
  ...
  [102 118 111]
  [106 119 111]
  [106 119 111]]

 ...

 [[ 56  48  23]
  [ 59  52  28]
  [ 

  [206 197 189]]]
frame : [[[166 145 108]
  [169 146 110]
  [169 145 111]
  ...
  [114 122 111]
  [115 121 107]
  [116 121 107]]

 [[166 147 112]
  [166 147 112]
  [166 147 112]
  ...
  [115 122 111]
  [115 121 107]
  [115 120 105]]

 [[164 147 112]
  [165 148 113]
  [164 147 112]
  ...
  [115 120 111]
  [114 119 107]
  [114 119 107]]

 ...

 [[ 61  50  29]
  [ 62  52  29]
  [ 63  52  28]
  ...
  [197 196 188]
  [197 194 188]
  [197 193 187]]

 [[ 63  51  27]
  [ 65  52  27]
  [ 67  52  26]
  ...
  [199 200 190]
  [199 199 188]
  [196 196 184]]

 [[ 66  54  27]
  [ 70  55  26]
  [ 70  52  21]
  ...
  [201 202 194]
  [198 200 191]
  [197 199 189]]]
frame : [[[165 142 114]
  [165 143 116]
  [164 145 118]
  ...
  [101 121 107]
  [100 121 107]
  [ 99 121 108]]

 [[165 142 112]
  [165 144 116]
  [165 147 119]
  ...
  [107 124 110]
  [106 123 108]
  [105 122 107]]

 [[167 142 112]
  [166 143 114]
  [167 147 117]
  ...
  [113 125 109]
  [111 122 105]
  [110 121 104]]

 ...

 [[ 66  41  32]
  

frame : [[[170 143 102]
  [170 144 105]
  [168 145 108]
  ...
  [107 120 124]
  [107 120 124]
  [105 118 121]]

 [[168 145 106]
  [169 146 107]
  [168 148 109]
  ...
  [104 119 124]
  [104 119 122]
  [103 118 121]]

 [[169 146 109]
  [170 147 110]
  [168 148 109]
  ...
  [ 98 119 124]
  [ 96 119 121]
  [ 96 119 121]]

 ...

 [[ 64  48  31]
  [ 60  49  33]
  [ 55  49  34]
  ...
  [202 194 186]
  [199 190 181]
  [198 188 180]]

 [[ 64  49  28]
  [ 61  50  30]
  [ 57  50  30]
  ...
  [204 198 189]
  [201 194 183]
  [197 190 180]]

 [[ 66  51  27]
  [ 63  52  30]
  [ 59  50  30]
  ...
  [204 200 189]
  [204 197 187]
  [200 193 182]]]
frame : [[[171 141 114]
  [170 143 113]
  [167 145 111]
  ...
  [103 115 119]
  [ 98 116 117]
  [ 99 118 118]]

 [[169 141 114]
  [170 144 114]
  [168 147 112]
  ...
  [108 118 120]
  [104 118 116]
  [103 118 116]]

 [[168 143 113]
  [170 144 114]
  [170 146 114]
  ...
  [111 120 118]
  [109 119 116]
  [108 118 115]]

 ...

 [[ 71  49  35]
  [ 72  49  36]
  [ 

frame : [[[170 148 109]
  [170 147 110]
  [168 144 110]
  ...
  [100 120 120]
  [ 98 121 117]
  [ 95 119 114]]

 [[172 149 110]
  [169 146 110]
  [168 144 112]
  ...
  [100 119 118]
  [ 99 120 116]
  [ 97 119 114]]

 [[174 148 110]
  [171 145 111]
  [170 143 113]
  ...
  [101 119 119]
  [100 119 115]
  [ 99 119 114]]

 ...

 [[ 68  45  35]
  [ 62  44  30]
  [ 59  45  26]
  ...
  [207 197 187]
  [205 194 181]
  [200 189 176]]

 [[ 69  50  33]
  [ 66  48  30]
  [ 64  48  29]
  ...
  [208 196 189]
  [207 196 185]
  [202 191 181]]

 [[ 68  53  29]
  [ 69  54  30]
  [ 70  55  32]
  ...
  [207 195 192]
  [208 195 192]
  [204 191 187]]]
frame : [[[159 146  95]
  [160 145  94]
  [162 145  97]
  ...
  [ 95 121 113]
  [103 121 110]
  [103 120 109]]

 [[161 146 100]
  [162 146  99]
  [163 146 100]
  ...
  [ 94 123 114]
  [ 99 122 110]
  [ 98 121 109]]

 [[164 146 106]
  [164 146 104]
  [164 147 103]
  ...
  [ 91 123 114]
  [ 92 122 110]
  [ 91 121 109]]

 ...

 [[ 65  51  32]
  [ 66  49  32]
  [ 

frame : [[[164 144 112]
  [159 145 111]
  [157 147 111]
  ...
  [110 120 113]
  [109 119 116]
  [110 120 117]]

 [[166 144 112]
  [162 145 110]
  [159 147 109]
  ...
  [107 119 112]
  [108 118 115]
  [110 120 117]]

 [[167 145 111]
  [165 146 110]
  [163 146 109]
  ...
  [107 117 111]
  [109 116 113]
  [112 119 116]]

 ...

 [[ 77  45  36]
  [ 78  46  37]
  [ 78  47  34]
  ...
  [193 196 184]
  [192 193 179]
  [190 190 176]]

 [[ 85  45  38]
  [ 84  49  37]
  [ 82  52  34]
  ...
  [199 198 188]
  [197 196 184]
  [194 192 181]]

 [[ 89  46  36]
  [ 88  51  35]
  [ 85  54  32]
  ...
  [201 199 189]
  [200 197 188]
  [195 193 184]]]
frame : [[[156 145 121]
  [160 144 124]
  [163 142 125]
  ...
  [ 85 120 117]
  [ 83 119 118]
  [ 83 120 120]]

 [[158 145 121]
  [161 143 121]
  [165 142 122]
  ...
  [ 92 120 117]
  [ 89 119 116]
  [ 89 119 117]]

 [[159 147 121]
  [162 145 120]
  [166 145 119]
  ...
  [ 97 120 115]
  [ 95 119 115]
  [ 95 119 115]]

 ...

 [[ 71  50  20]
  [ 73  51  19]
  [ 

frame : [[[156 145 107]
  [161 144 107]
  [168 145 108]
  ...
  [112 122 112]
  [113 121 109]
  [114 121 108]]

 [[159 145 105]
  [162 145 104]
  [167 145 103]
  ...
  [107 121 111]
  [109 121 109]
  [109 121 108]]

 [[161 145 105]
  [162 145 104]
  [166 146 104]
  ...
  [102 121 113]
  [102 120 109]
  [102 120 109]]

 ...

 [[ 68  50  13]
  [ 66  48  18]
  [ 65  48  25]
  ...
  [201 194 187]
  [197 193 182]
  [192 188 177]]

 [[ 74  47  13]
  [ 71  46  18]
  [ 68  46  23]
  ...
  [207 195 194]
  [199 191 187]
  [197 189 185]]

 [[ 76  52  20]
  [ 74  51  23]
  [ 73  51  28]
  ...
  [208 196 194]
  [203 195 191]
  [199 191 187]]]
frame : [[[171 144 105]
  [172 143 106]
  [171 143 107]
  ...
  [100 121 111]
  [ 98 119 108]
  [ 98 119 108]]

 [[169 144 105]
  [171 144 108]
  [170 144 110]
  ...
  [100 119 114]
  [100 118 112]
  [101 118 112]]

 [[169 146 107]
  [170 146 109]
  [171 145 111]
  ...
  [101 118 116]
  [100 117 113]
  [102 118 115]]

 ...

 [[ 60  49  28]
  [ 62  51  27]
  [ 

frame : [[[163 143 120]
  [168 146 119]
  [170 147 115]
  ...
  [ 97 119 113]
  [ 96 123 113]
  [ 95 123 113]]

 [[165 143 120]
  [169 146 119]
  [170 147 115]
  ...
  [ 97 121 113]
  [ 96 123 112]
  [ 95 123 111]]

 [[169 143 118]
  [171 146 118]
  [168 146 114]
  ...
  [ 99 120 115]
  [ 96 121 112]
  [ 96 121 112]]

 ...

 [[ 64  46  36]
  [ 64  46  37]
  [ 64  46  36]
  ...
  [197 194 190]
  [195 192 186]
  [193 190 183]]

 [[ 67  46  36]
  [ 68  46  35]
  [ 71  49  35]
  ...
  [200 196 191]
  [198 193 187]
  [195 190 183]]

 [[ 72  50  36]
  [ 75  51  34]
  [ 79  54  33]
  ...
  [202 196 192]
  [202 194 188]
  [198 191 184]]]
frame : [[[162 143 115]
  [162 143 115]
  [164 143 115]
  ...
  [111 122 117]
  [111 122 116]
  [110 121 115]]

 [[164 145 110]
  [166 144 111]
  [168 144 112]
  ...
  [109 123 114]
  [106 122 112]
  [105 121 110]]

 [[166 145 108]
  [168 144 110]
  [170 143 112]
  ...
  [107 124 111]
  [103 122 107]
  [101 121 105]]

 ...

 [[ 70  47  26]
  [ 68  50  29]
  [ 

frame : [[[170 143 112]
  [169 143 112]
  [169 145 113]
  ...
  [115 121 114]
  [115 120 115]
  [113 119 114]]

 [[170 143 112]
  [169 145 113]
  [168 146 114]
  ...
  [110 124 115]
  [111 123 118]
  [110 122 117]]

 [[169 145 111]
  [170 147 114]
  [170 147 115]
  ...
  [101 124 113]
  [103 123 115]
  [103 123 115]]

 ...

 [[ 56  48  33]
  [ 59  47  32]
  [ 63  46  32]
  ...
  [195 188 183]
  [194 188 184]
  [192 187 183]]

 [[ 61  53  36]
  [ 63  49  32]
  [ 69  47  31]
  ...
  [198 190 181]
  [196 191 184]
  [196 191 185]]

 [[ 64  57  37]
  [ 69  54  35]
  [ 74  51  33]
  ...
  [198 191 182]
  [194 191 184]
  [193 191 185]]]
frame : [[[152 146 113]
  [154 145 111]
  [158 145 112]
  ...
  [105 117 112]
  [108 118 113]
  [108 118 113]]

 [[152 146 113]
  [154 144 110]
  [160 144 112]
  ...
  [107 119 115]
  [109 120 112]
  [109 120 112]]

 [[155 146 115]
  [158 145 114]
  [162 144 113]
  ...
  [109 120 117]
  [114 122 115]
  [114 122 114]]

 ...

 [[ 64  50  14]
  [ 65  53  14]
  [ 

frame : [[[167 141 105]
  [167 143 107]
  [166 145 108]
  ...
  [108 122 112]
  [105 120 112]
  [105 120 112]]

 [[166 141 109]
  [166 143 108]
  [167 147 107]
  ...
  [111 124 115]
  [110 121 113]
  [109 120 112]]

 [[167 141 114]
  [168 144 111]
  [170 148 109]
  ...
  [113 124 115]
  [115 121 112]
  [113 119 109]]

 ...

 [[ 56  46  29]
  [ 58  46  29]
  [ 61  44  28]
  ...
  [ 95  70  54]
  [100  70  54]
  [102  71  56]]

 [[ 61  47  30]
  [ 66  48  30]
  [ 70  47  26]
  ...
  [100  73  54]
  [102  71  54]
  [103  73  55]]

 [[ 64  52  33]
  [ 68  54  32]
  [ 72  52  29]
  ...
  [101  73  51]
  [103  73  53]
  [105  75  56]]]
frame : [[[171 144 105]
  [172 144 104]
  [173 144 103]
  ...
  [ 98 119 109]
  [ 96 117 104]
  [ 96 117 104]]

 [[172 144 110]
  [176 142 110]
  [181 142 112]
  ...
  [100 120 110]
  [ 96 117 104]
  [ 96 117 104]]

 [[171 143 116]
  [176 143 117]
  [180 143 116]
  ...
  [101 120 110]
  [ 98 120 106]
  [ 98 120 106]]

 ...

 [[ 69  46  35]
  [ 67  41  37]
  [ 

frame : [[[161 142 114]
  [159 142 114]
  [159 142 114]
  ...
  [ 98 119 114]
  [106 118 115]
  [107 118 115]]

 [[161 141 116]
  [162 143 117]
  [162 143 117]
  ...
  [101 120 117]
  [107 119 116]
  [109 120 117]]

 [[167 144 116]
  [168 145 119]
  [165 144 118]
  ...
  [103 119 117]
  [110 120 117]
  [111 120 117]]

 ...

 [[ 67  48  29]
  [ 71  46  28]
  [ 75  45  27]
  ...
  [ 72  62  29]
  [ 77  63  35]
  [ 76  62  34]]

 [[ 69  47  31]
  [ 73  46  28]
  [ 77  45  25]
  ...
  [ 78  63  30]
  [ 81  63  33]
  [ 82  63  33]]

 [[ 72  49  30]
  [ 75  49  29]
  [ 79  50  28]
  ...
  [ 82  64  32]
  [ 84  63  33]
  [ 83  62  32]]]


### Explanation

In [ ]:
mp_face_mesh = mp.solutions.face_mesh
LEFT_EYE =[ 362, 382, 381, 380, 374, 373, 390, 249, 263, 466, 388, 387, 386, 385,384, 398 ]
# right eyes indices
RIGHT_EYE=[ 33, 7, 163, 144, 145, 153, 154, 155, 133, 173, 157, 158, 159, 160, 161 , 246 ] 
LEFT_IRIS = [474,475, 476, 477]
RIGHT_IRIS = [469, 470, 471, 472]

Cordinated can be found in the following link. The daigram deosnot provide the cordinats on iris
https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/face_mesh_connections.py

In [ ]:
cap = cv.VideoCapture(0)

Turning on the video camera

In [ ]:
with mp_face_mesh.FaceMesh(
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
) as face_mesh

with statement in Python is used in exception handling to make the code cleaner and much more readable. It simplifies the management of common resources like file streams. Observe the following code example on how the use of with statement makes code cleaner.

using with statement
with open('file_path', 'w') as file:
    file.write('hello world !')
    
    
MAX_NUM_FACES
Maximum number of faces to detect. Default to 1.

REFINE_LANDMARKS
Whether to further refine the landmark coordinates around the eyes and lips, and output additional landmarks around the irises by applying the Attention Mesh Model. Default to false.

MIN_DETECTION_CONFIDENCE
Minimum confidence value ([0.0, 1.0]) from the face detection model for the detection to be considered successful. Default to 0.5.

MIN_TRACKING_CONFIDENCE
Minimum confidence value ([0.0, 1.0]) from the landmark-tracking model for the face landmarks to be considered tracked successfully, or otherwise face detection will be invoked automatically on the next input image. Setting it to a higher value can increase robustness of the solution, at the expense of a higher latency. Ignored if static_image_mode is true, where face detection simply runs on every image. Default to 0.5.
    

In [ ]:
while True:
        ret, frame = cap.read()
        if not ret:
            break

Infinite Loop

Capture frame-by-frame

ret is a boolean variable that returns true if the frame is available.
frame is an image array vector captured based on the default frames per second defined explicitly or implicitly

In [ ]:
frame = cv.flip(frame, 1)

Syntax: cv2.cv.flip(src, flipCode[, dst] )

Parameters:
src: Input array.
dst: Output array of the same size and type as src.
flip code: A flag to specify how to flip the array; 0 means flipping around the x-axis and positive value (for example, 1) means flipping around y-axis. Negative value (for example, -1) means flipping around both axes.

Return Value: It returns an image.

Ahh just flipping the image for the convenice of the user 

rgb_frame = cv.cvtColor(frame, cv.COLOR_BGR2RGB)

In [8]:
frame.shape[:2]

(480, 640)

height = img.shape[0]
width = img.shape[1]
channels = img.shape[2]

Height represents the number of pixel rows in the image or the number of pixels in each column of the image array.
Width represents the number of pixel columns in the image or the number of pixels in each row of the image array.
Number of Channels represents the number of components used to represent each pix

In [12]:
results.multi_face_landmarks[0].landmark


[x: 0.3538835048675537
y: 0.6848288178443909
z: -0.01327614113688469
, x: 0.35604172945022583
y: 0.655215322971344
z: -0.044171590358018875
, x: 0.3569695055484772
y: 0.6618587970733643
z: -0.018333451822400093
, x: 0.35417476296424866
y: 0.6092816591262817
z: -0.03911159187555313
, x: 0.3570462167263031
y: 0.6434957981109619
z: -0.04920976981520653
, x: 0.359444797039032
y: 0.6253679990768433
z: -0.04857804998755455
, x: 0.36632877588272095
y: 0.5787176489830017
z: -0.03419409692287445
, x: 0.3086147904396057
y: 0.5595347881317139
z: 0.006564034149050713
, x: 0.3697971701622009
y: 0.5509164333343506
z: -0.03509277105331421
, x: 0.3712216913700104
y: 0.5355885624885559
z: -0.04080355539917946
, x: 0.37863221764564514
y: 0.4659045338630676
z: -0.043801192194223404
, x: 0.3537147343158722
y: 0.6890467405319214
z: -0.0109652578830719
, x: 0.35368475317955017
y: 0.6935473680496216
z: -0.007151127327233553
, x: 0.35389819741249084
y: 0.6966160535812378
z: -0.000833942904137075
, x: 0.354083

np.array([np.multiply([p.x, p.y], [img_w, img_h]).astype(int)
          

In [ ]:
if results.multi_face_landmarks:

If face land marks are availalbe in the frame 

In [ ]:
mesh_points=np.array([np.multiply([p.x, p.y], [img_w, img_h]).astype(int) for p in results.multi_face_landmarks[0].landmark])

Obtain the mesh points of all the available cordinates 


In [1]:
(l_cx, l_cy), l_radius = cv.minEnclosingCircle(mesh_points[LEFT_IRIS])
(r_cx, r_cy), r_radius = cv.minEnclosingCircle(mesh_points[RIGHT_IRIS])

NameError: name 'cv' is not defined

◆ minEnclosingCircle()
void cv::minEnclosingCircle	(	InputArray 	points,
Point2f & 	center,
float & 	radius 
)		
Python:
cv.minEnclosingCircle(	points	) ->	center, radius
#include <opencv2/imgproc.hpp>

Finds a circle of the minimum area enclosing a 2D point set.

The function finds the minimal enclosing circle of a 2D point set using an iterative algorithm.

Parameters
points	Input vector of 2D points, stored in std::vector<> or Mat
center	Output center of the circle.
radius	Output radius of the circle.
Examples:


obtaining the center points and the radius of the minimum circle 


In [ ]:
center_left = np.array([l_cx, l_cy], dtype=np.int32)
center_right = np.array([r_cx, r_cy], dtype=np.int32)
cv.circle(frame, center_left, int(l_radius), (255,0,255), 1, cv.LINE_AA)
cv.circle(frame, center_right, int(r_radius), (255,0,255), 1, cv.LINE_AA)
            

Iddentify the center cordinates and draw the circle 